CREATE DATABASE SCNF;

USE SCNF;

CREATE TABLE INFOS
(
	ID_INFO INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) UNIQUE NOT NULL,
	RG VARCHAR(13) UNIQUE NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	CEP VARCHAR(11) NOT NULL,
	SEXO VARCHAR(20),
	EMAIL VARCHAR(150) UNIQUE NOT NULL,
	EMAILINST VARCHAR(150) UNIQUE,
	TELEFONE SMALLINT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	TITULO_ELEITOR VARCHAR(15) UNIQUE NOT NULL,
	RESERVISTA BIT UNIQUE
);

CREATE TABLE TRANSFERENCIAS(
	ID_TRANSFERENCIA INT IDENTITY PRIMARY KEY,
	DATA_TRANSFERENCIA DATE,
	INSTUICAO_ORIGEM VARCHAR(255),
	REAPROVEITAMENTO VARCHAR(255),
	OBSERVACOES VARCHAR(255)
);

CREATE TABLE NOTAS(
	ID_NOTAS INT IDENTITY PRIMARY KEY,
	NP1 FLOAT,
	NP2 FLOAT,
	TRABALHOS FLOAT,
	EXAME FLOAT,
	SUB FLOAT,
	PROJ_INTE FLOAT,
	MEDIA FLOAT
);

CREATE TABLE CALENDARIO
(
	ID_CALENDARIO INT IDENTITY PRIMARY KEY,
	DATA_PERIODO_ESCOLAR VARCHAR(255),
	DATA_AVALIACOES VARCHAR(255),
	DATA_NOTAS_PROFESSORES VARCHAR(255),
	DATAS VARCHAR(255)
);

CREATE TABLE MATRICULAS(
	ID_MATRICULA INT IDENTITY PRIMARY KEY,
	ID_TRANSFERENCIA INT FOREIGN KEY REFERENCES TRANSFERENCIAS (ID_TRANSFERENCIA),
	STATUS_MATRICULA BIT,
	DATA_INICIO_CURSO DATE NOT NULL,
	DATA_TERMINO_CURSO DATE,
	DATA_TRANCAMENTO DATE,
	OBSERVACOES VARCHAR(255)
);

CREATE TABLE MATERIAS(
	ID_MATERIA INT IDENTITY PRIMARY KEY,
	ID_NOTAS INT FOREIGN KEY REFERENCES NOTAS (ID_NOTAS),
	NOME VARCHAR(150) NOT NULL,
	CARGA_HORARIA VARCHAR(10),
	FREQUENCIA INT,
	NUMERO_AULAS INT,
	DATA_MATERIA DATE,
	STATUS_MATERIA BIT,
	OBSERVACOES VARCHAR(255),
	
);

CREATE TABLE CAMPUS(
	ID_CAMPUS INT IDENTITY PRIMARY KEY,
	NOME_CAMPUS VARCHAR(255) NOT NULL,
	ENDERECO_CAMPUS VARCHAR(255) NOT NULL,
	CEP_CAMPUS VARCHAR(11) NOT NULL,
	TELEFONE_CAMPUS VARCHAR(17) NOT NULL,
	QUANT_ALUNOS INT
);

CREATE TABLE CURSOS(
	ID_CURSO INT IDENTITY PRIMARY KEY,
	ID_MATERIA_CURSO INT FOREIGN KEY REFERENCES MATERIAS (ID_MATERIA),
	NOME VARCHAR(150) NOT NULL,
	DURACAO INT,
	OBSERVACOES VARCHAR(255)
);

CREATE TABLE CAMPUS_CURSOS(
	ID_CAMPUS_CURSOS INT IDENTITY PRIMARY KEY,
	ID_CAMPUS INT FOREIGN KEY REFERENCES CAMPUS (ID_CAMPUS),
	ID_CURSOS INT FOREIGN KEY REFERENCES CURSOS (ID_CURSO),
	STATUS_CAMPOSCURSOS BIT
);

CREATE TABLE PROFESSORES
(
	ID_PROFESSOR INT IDENTITY PRIMARY KEY,
	ID_INFO_PROFESSOR INT FOREIGN KEY REFERENCES INFOS (ID_INFO),
	ID_MATERIA INT FOREIGN KEY REFERENCES MATERIAS (ID_MATERIA),
	ID_CALENDARIO INT FOREIGN KEY REFERENCES CALENDARIO (ID_CALENDARIO),
	SENHA VARCHAR(255) NOT NULL,
	STATUS_PROFESSOR BIT

);

CREATE TABLE ALUNOS
(
	ID_ALUNO INT IDENTITY PRIMARY KEY,
	ID_INFO_ALUNO INT FOREIGN KEY REFERENCES INFOS (ID_INFO),
	ID_MATRICULA INT FOREIGN KEY REFERENCES MATRICULAS (ID_MATRICULA),
	ID_MATERIA INT FOREIGN KEY REFERENCES MATERIAS (ID_MATERIA),
	ID_CALENDARIO INT FOREIGN KEY REFERENCES CALENDARIO (ID_CALENDARIO),
	TIPO_INGRESSO VARCHAR(255),
	SENHA VARCHAR(255) NOT NULL,
	STATUS_ALUNO BIT
);

CREATE TABLE TURMAS
(
	ID_TURMAS INT IDENTITY PRIMARY KEY,
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNOS (ID_ALUNO),
	ID_PROFESSOR INT FOREIGN KEY REFERENCES PROFESSORES (ID_PROFESSOR),
	CODIGO VARCHAR(255),
	STATUS_TURMA BIT,
	PERIODO VARCHAR(255)
);

CREATE TABLE ADM
(
	ID_ADM INT IDENTITY PRIMARY KEY,
	ID_INFO_ADM INT FOREIGN KEY REFERENCES INFOS (ID_INFO),
	ID_PROFESSOR_ADM INT FOREIGN KEY REFERENCES PROFESSORES (ID_PROFESSOR),
	ID_ALUNO_ADM INT FOREIGN KEY REFERENCES ALUNOS (ID_ALUNO),
	ID_MATRICULA_ADM INT FOREIGN KEY REFERENCES MATRICULAS (ID_MATRICULA),
	ID_CAMPUS_ADM INT FOREIGN KEY REFERENCES CAMPUS (ID_CAMPUS),
	ID_CALENDARIO INT FOREIGN KEY REFERENCES CALENDARIO (ID_CALENDARIO),
	ID_TURMAS INT FOREIGN KEY REFERENCES TURMAS (ID_TURMAS),
	CARGO VARCHAR(255) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	STATUS BIT

);